apiVersion: v1
kind: Service
metadata:
  name: iotagent-manager
spec:
  selector:
    app: iotagent-manager
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  type: ClusterIP
